[2025-05-10T19:40:38.554+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-10T19:40:38.634+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_model_pipeline.train_data manual__2025-05-10T19:40:24.872104+00:00 [queued]>
[2025-05-10T19:40:38.657+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_model_pipeline.train_data manual__2025-05-10T19:40:24.872104+00:00 [queued]>
[2025-05-10T19:40:38.659+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-10T19:40:38.700+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_data> on 2025-05-10 19:40:24.872104+00:00
[2025-05-10T19:40:38.758+0000] {standard_task_runner.py:63} INFO - Started process 5852 to run task
[2025-05-10T19:40:38.781+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'diabetes_model_pipeline', 'train_data', 'manual__2025-05-10T19:40:24.872104+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpuou56h21']
[2025-05-10T19:40:38.800+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask train_data
[2025-05-10T19:40:39.045+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_model_pipeline.train_data manual__2025-05-10T19:40:24.872104+00:00 [running]> on host cc11726e1520
[2025-05-10T19:40:39.519+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='diabetes_model_pipeline' AIRFLOW_CTX_TASK_ID='train_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-10T19:40:24.872104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-10T19:40:24.872104+00:00'
[2025-05-10T19:40:39.523+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-10T19:40:40.781+0000] {logging_mixin.py:188} INFO - Connected to Minio. Buckets: ['mlflow', 'mlflows3']
[2025-05-10T19:40:40.782+0000] {logging_mixin.py:188} INFO - Version de mlflow: 2.17.2
[2025-05-10T19:40:40.783+0000] {logging_mixin.py:188} INFO - Leyendo datos de la tabla diabetes_train_processed...
[2025-05-10T19:40:40.813+0000] {base.py:84} INFO - Using connection ID 'postgres_airflow_conn' for task execution.
[2025-05-10T19:40:40.887+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-05-10T19:40:42.385+0000] {logging_mixin.py:188} INFO - Datos de entrenamiento:
[2025-05-10T19:40:42.386+0000] {logging_mixin.py:188} INFO - - Forma: (61059, 16)
[2025-05-10T19:40:42.386+0000] {logging_mixin.py:188} INFO - - Columnas: ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'target']
[2025-05-10T19:40:42.387+0000] {logging_mixin.py:188} INFO - - Primeras 5 filas:
[2025-05-10T19:40:42.543+0000] {logging_mixin.py:188} INFO -    feature_0  feature_1  feature_2  ...  feature_13  feature_14  target
0  -0.469946  -1.639515   0.390360  ...         6.0         3.0     YES
1   1.540265   0.397996  -0.786066  ...         6.0         3.0     YES
2  -1.140016  -1.741390  -0.786066  ...         0.0         3.0      NO
3  -0.804981  -1.435764  -0.786066  ...         0.0         3.0     YES
4  -0.469946  -0.773573   2.743213  ...         0.0         3.0      NO

[5 rows x 16 columns]
[2025-05-10T19:40:42.549+0000] {logging_mixin.py:188} INFO - DistribuciÔøΩn de clases (entrenamiento):
[2025-05-10T19:40:42.568+0000] {logging_mixin.py:188} INFO - target
NO     32918
YES    28141
Name: count, dtype: int64
[2025-05-10T19:40:42.569+0000] {logging_mixin.py:188} INFO - Aplicando undersampling al conjunto de entrenamiento...
[2025-05-10T19:40:42.629+0000] {logging_mixin.py:188} INFO - Class distribution before undersampling:
[2025-05-10T19:40:42.630+0000] {logging_mixin.py:188} INFO -   Class NO: 32918 samples
[2025-05-10T19:40:42.630+0000] {logging_mixin.py:188} INFO -   Class YES: 28141 samples
[2025-05-10T19:40:42.730+0000] {logging_mixin.py:188} INFO - Class distribution after undersampling:
[2025-05-10T19:40:42.730+0000] {logging_mixin.py:188} INFO -   Class NO: 28141 samples
[2025-05-10T19:40:42.731+0000] {logging_mixin.py:188} INFO -   Class YES: 28141 samples
[2025-05-10T19:40:43.428+0000] {logging_mixin.py:188} WARNING - 2025/05/10 19:40:43 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-10T19:40:43.907+0000] {logging_mixin.py:188} INFO - Iniciando entrenamiento
[2025-05-10T19:40:44.234+0000] {logging_mixin.py:188} INFO - Entrenamiento finalizado
[2025-05-10T19:40:52.103+0000] {logging_mixin.py:188} WARNING - 2025/05/10 19:40:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-10T19:40:52.142+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-05-10T19:40:52.617+0000] {logging_mixin.py:188} WARNING - Registered model 'svm-model' already exists. Creating a new version of this model...
[2025-05-10T19:40:52.683+0000] {logging_mixin.py:188} WARNING - 2025/05/10 19:40:52 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: svm-model, version 2
[2025-05-10T19:40:52.684+0000] {logging_mixin.py:188} WARNING - Created version '2' of model 'svm-model'.
[2025-05-10T19:40:52.715+0000] {logging_mixin.py:188} INFO - Ultima versi√≥n: 2
[2025-05-10T19:40:52.745+0000] {logging_mixin.py:188} WARNING - 2025/05/10 19:40:52 INFO mlflow.tracking._tracking_service.client: üèÉ View run svm_training at: http://10.43.101.168:31485/#/experiments/1/runs/9f09494ee1c941f9b4a118f5b658866d.
[2025-05-10T19:40:52.746+0000] {logging_mixin.py:188} WARNING - 2025/05/10 19:40:52 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://10.43.101.168:31485/#/experiments/1.
[2025-05-10T19:40:52.790+0000] {python.py:237} INFO - Done. Returned value was: Entrenamiento completado
[2025-05-10T19:40:52.791+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-10T19:40:52.894+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=diabetes_model_pipeline, task_id=train_data, execution_date=20250510T194024, start_date=20250510T194038, end_date=20250510T194052
[2025-05-10T19:40:52.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-10T19:40:53.073+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-10T19:40:53.076+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
