[2025-05-03T07:55:13.786+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T07:55:13.901+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_data_pipeline.preprocess_train_data manual__2025-05-03T07:54:35.257746+00:00 [queued]>
[2025-05-03T07:55:13.929+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_data_pipeline.preprocess_train_data manual__2025-05-03T07:54:35.257746+00:00 [queued]>
[2025-05-03T07:55:13.931+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T07:55:13.970+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): preprocess_train_data> on 2025-05-03 07:54:35.257746+00:00
[2025-05-03T07:55:14.014+0000] {standard_task_runner.py:63} INFO - Started process 1830 to run task
[2025-05-03T07:55:14.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_data_pipeline', 'preprocess_train_data', 'manual__2025-05-03T07:54:35.257746+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/process_and_clean_data.py', '--cfg-path', '/tmp/tmp02mqyd8v']
[2025-05-03T07:55:14.050+0000] {standard_task_runner.py:91} INFO - Job 240: Subtask preprocess_train_data
[2025-05-03T07:55:14.336+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_data_pipeline.preprocess_train_data manual__2025-05-03T07:54:35.257746+00:00 [running]> on host e89618938543
[2025-05-03T07:55:14.691+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_train_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T07:54:35.257746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T07:54:35.257746+00:00'
[2025-05-03T07:55:14.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T07:55:21.397+0000] {process_and_clean_data.py:317} INFO - Iniciando preprocesamiento de datos train...
[2025-05-03T07:55:21.652+0000] {warnings.py:109} WARNING - /opt/***/dags/process_and_clean_data.py:169: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diabetes_num['service_utilization'] = (df_diabetes_num['number_outpatient'] +

[2025-05-03T07:55:25.445+0000] {process_and_clean_data.py:338} INFO - Preprocessor guardado en: /opt/***/data/models/diabetes_preprocessor.pkl
[2025-05-03T07:55:28.346+0000] {process_and_clean_data.py:382} INFO - âœ“ Datos train preprocesados exitosamente:
[2025-05-03T07:55:28.348+0000] {process_and_clean_data.py:383} INFO -    - Filas: 61059
[2025-05-03T07:55:28.348+0000] {process_and_clean_data.py:384} INFO -    - Columnas: 84
[2025-05-03T07:55:28.666+0000] {python.py:237} INFO - Done. Returned value was:               0         1         2  ...  target  encounter_id  patient_nbr
0     -0.469946 -1.639515  0.390360  ...      NO     230121744     40425831
1      1.540265  0.397996 -0.786066  ...     YES      82802424      2937096
2     -1.140016 -1.741390 -0.786066  ...      NO     158382600     60988536
3     -0.804981 -1.435764 -0.786066  ...      NO     270885012     42274989
4     -0.469946 -0.773573  2.743213  ...      NO     266768154     88983945
...         ...       ...       ...  ...     ...           ...          ...
61054 -0.469946 -0.620759 -0.786066  ...      NO     230847720     38661453
61055 -0.134911  0.194245 -0.197853  ...      NO      59109546      5033412
61056 -1.140016 -0.569822 -0.786066  ...      NO      51604626     18682812
61057 -0.134911 -0.213257  1.566786  ...      NO      75118320      1875321
61058  0.870195 -0.620759 -0.786066  ...      NO     160141998     40815144

[61059 rows x 84 columns]
[2025-05-03T07:55:28.903+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T07:55:29.011+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/serialization/serializers/pandas.py:49: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(o)

[2025-05-03T07:55:29.874+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=diabetes_data_pipeline, task_id=preprocess_train_data, execution_date=20250503T075435, start_date=20250503T075513, end_date=20250503T075529
[2025-05-03T07:55:30.072+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-03T07:55:30.253+0000] {taskinstance.py:3482} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-05-03T07:55:30.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
