[2025-05-03T09:02:26.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T09:02:26.503+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_undersampling_prediction.apply_undersampling manual__2025-05-03T09:01:52.813872+00:00 [queued]>
[2025-05-03T09:02:26.536+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_undersampling_prediction.apply_undersampling manual__2025-05-03T09:01:52.813872+00:00 [queued]>
[2025-05-03T09:02:26.537+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T09:02:26.599+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): apply_undersampling> on 2025-05-03 09:01:52.813872+00:00
[2025-05-03T09:02:26.638+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2025-05-03T09:02:26.654+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_undersampling_prediction', 'apply_undersampling', 'manual__2025-05-03T09:01:52.813872+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmp07a8aboq']
[2025-05-03T09:02:26.668+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask apply_undersampling
[2025-05-03T09:02:26.812+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_undersampling_prediction.apply_undersampling manual__2025-05-03T09:01:52.813872+00:00 [running]> on host 31e5ce530290
[2025-05-03T09:02:27.028+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_undersampling_prediction' AIRFLOW_CTX_TASK_ID='apply_undersampling' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T09:01:52.813872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T09:01:52.813872+00:00'
[2025-05-03T09:02:27.029+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T09:02:30.508+0000] {model.py:261} INFO - Aplicando undersampling a datos de entrenamiento...
[2025-05-03T09:02:30.509+0000] {model.py:262} INFO -    - Datos originales: X_shape=(61059, 20), y_shape=(61059,)
[2025-05-03T09:02:30.701+0000] {model.py:184} INFO - Distribuci�n de clases antes del undersampling:
[2025-05-03T09:02:30.702+0000] {model.py:186} INFO -   Clase target: 61059 muestras
[2025-05-03T09:02:30.713+0000] {model.py:285} ERROR -  Error al aplicar undersampling: Esta funci�n solo soporta problemas de clasificaci�n binaria
[2025-05-03T09:02:30.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T09:02:30.713+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/model.py", line 266, in apply_undersampling
    X_resampled, y_resampled = perform_undersampling_from_transformed(
  File "/opt/airflow/dags/model.py", line 190, in perform_undersampling_from_transformed
    raise ValueError("Esta funci�n solo soporta problemas de clasificaci�n binaria")
ValueError: Esta funci�n solo soporta problemas de clasificaci�n binaria
[2025-05-03T09:02:30.749+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_undersampling_prediction, task_id=apply_undersampling, execution_date=20250503T090152, start_date=20250503T090226, end_date=20250503T090230
[2025-05-03T09:02:30.795+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 280 for task apply_undersampling (Esta funci�n solo soporta problemas de clasificaci�n binaria; 185)
[2025-05-03T09:02:31.000+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T09:02:31.180+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T09:02:31.195+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
