[2025-04-02T00:03:13.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-02T00:03:13.412+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model.train_model manual__2025-04-02T00:03:08.393095+00:00 [queued]>
[2025-04-02T00:03:13.426+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model.train_model manual__2025-04-02T00:03:08.393095+00:00 [queued]>
[2025-04-02T00:03:13.427+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-02T00:03:13.451+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_model> on 2025-04-02 00:03:08.393095+00:00
[2025-04-02T00:03:13.471+0000] {standard_task_runner.py:63} INFO - Started process 23347 to run task
[2025-04-02T00:03:13.482+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_model', 'train_model', 'manual__2025-04-02T00:03:08.393095+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/tmp/tmpo82iz57o']
[2025-04-02T00:03:13.488+0000] {standard_task_runner.py:91} INFO - Job 608: Subtask train_model
[2025-04-02T00:03:13.553+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model.train_model manual__2025-04-02T00:03:08.393095+00:00 [running]> on host d34402ef6e0d
[2025-04-02T00:03:13.670+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_model' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:03:08.393095+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T00:03:08.393095+00:00'
[2025-04-02T00:03:13.672+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-02T00:03:13.692+0000] {logging_mixin.py:188} INFO - MLflow Version: 2.17.2
[2025-04-02T00:03:13.702+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-02T00:03:13.713+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-04-02T00:03:14.245+0000] {logging_mixin.py:188} WARNING - 2025/04/02 00:03:14 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-02T00:03:14.528+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-04-02T00:03:24.209+0000] {logging_mixin.py:188} WARNING - 2025/04/02 00:03:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-04-02T00:03:24.685+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-04-02T00:03:25.755+0000] {logging_mixin.py:188} WARNING - Registered model 'svm-model' already exists. Creating a new version of this model...
[2025-04-02T00:03:25.820+0000] {logging_mixin.py:188} WARNING - 2025/04/02 00:03:25 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: svm-model, version 9
[2025-04-02T00:03:25.821+0000] {logging_mixin.py:188} WARNING - Created version '9' of model 'svm-model'.
[2025-04-02T00:03:25.824+0000] {warnings.py:109} WARNING - /opt/***/dags/train.py:103: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2025-04-02T00:03:25.891+0000] {logging_mixin.py:188} WARNING - 2025/04/02 00:03:25 INFO mlflow.tracking._tracking_service.client: üèÉ View run svm_artifacts at: http://mlflow:5000/#/experiments/1/runs/397f3835560a48d597df6fd8a9b04fe0.
[2025-04-02T00:03:25.892+0000] {logging_mixin.py:188} WARNING - 2025/04/02 00:03:25 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-04-02T00:03:25.915+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-02T00:03:25.916+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-02T00:03:25.930+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=train_model, task_id=train_model, execution_date=20250402T000308, start_date=20250402T000313, end_date=20250402T000325
[2025-04-02T00:03:26.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-02T00:03:26.062+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T00:03:26.063+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
