[2025-05-03T07:48:36.417+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T07:48:36.508+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_data_pipeline.save_test_data manual__2025-05-03T07:44:33.093757+00:00 [queued]>
[2025-05-03T07:48:36.531+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_data_pipeline.save_test_data manual__2025-05-03T07:44:33.093757+00:00 [queued]>
[2025-05-03T07:48:36.532+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-03T07:48:36.582+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_test_data> on 2025-05-03 07:44:33.093757+00:00
[2025-05-03T07:48:36.644+0000] {standard_task_runner.py:63} INFO - Started process 1671 to run task
[2025-05-03T07:48:36.670+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_data_pipeline', 'save_test_data', 'manual__2025-05-03T07:44:33.093757+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/process_and_clean_data.py', '--cfg-path', '/tmp/tmpyn05ga_k']
[2025-05-03T07:48:36.676+0000] {standard_task_runner.py:91} INFO - Job 235: Subtask save_test_data
[2025-05-03T07:48:36.792+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_data_pipeline.save_test_data manual__2025-05-03T07:44:33.093757+00:00 [running]> on host e89618938543
[2025-05-03T07:48:36.995+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_data_pipeline' AIRFLOW_CTX_TASK_ID='save_test_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T07:44:33.093757+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T07:44:33.093757+00:00'
[2025-05-03T07:48:36.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T07:48:38.282+0000] {process_and_clean_data.py:561} INFO - Guardando datos procesados en tabla diabetes_test_processed...
[2025-05-03T07:48:38.318+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-03T07:48:38.319+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:48:38.324+0000] {sql.py:457} INFO - Running statement: DROP TABLE IF EXISTS diabetes_test_processed, parameters: None
[2025-05-03T07:48:38.415+0000] {sql.py:466} INFO - Rows affected: 0
[2025-05-03T07:48:38.428+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:48:38.449+0000] {sql.py:457} INFO - Running statement: 
        CREATE TABLE diabetes_test_processed (
            `feature_0` DOUBLE, `feature_1` DOUBLE, `feature_2` DOUBLE, `feature_3` DOUBLE, `feature_4` DOUBLE, `feature_5` DOUBLE, `feature_6` DOUBLE, `feature_7` DOUBLE, `feature_8` DOUBLE, `feature_9` BIGINT, `feature_10` BIGINT, `feature_11` BIGINT, `feature_12` BIGINT, `feature_13` BIGINT, `feature_14` BIGINT, `feature_15` BIGINT, `feature_16` BIGINT, `feature_17` BIGINT, `feature_18` BIGINT, `feature_19` BIGINT, `feature_20` BIGINT, `feature_21` BIGINT, `feature_22` BIGINT, `feature_23` BIGINT, `feature_24` BIGINT, `feature_25` BIGINT, `feature_26` BIGINT, `feature_27` BIGINT, `feature_28` BIGINT, `feature_29` BIGINT, `feature_30` BIGINT, `feature_31` BIGINT, `feature_32` BIGINT, `feature_33` BIGINT, `feature_34` BIGINT, `feature_35` BIGINT, `feature_36` BIGINT, `feature_37` BIGINT, `feature_38` BIGINT, `feature_39` BIGINT, `feature_40` BIGINT, `feature_41` BIGINT, `feature_42` BIGINT, `feature_43` BIGINT, `feature_44` BIGINT, `feature_45` BIGINT, `feature_46` BIGINT, `feature_47` BIGINT, `feature_48` BIGINT, `feature_49` BIGINT, `feature_50` BIGINT, `feature_51` BIGINT, `feature_52` BIGINT, `feature_53` BIGINT, `feature_54` BIGINT, `feature_55` BIGINT, `feature_56` BIGINT, `feature_57` BIGINT, `feature_58` BIGINT, `feature_59` BIGINT, `feature_60` BIGINT, `feature_61` BIGINT, `feature_62` BIGINT, `feature_63` BIGINT, `feature_64` BIGINT, `feature_65` BIGINT, `feature_66` BIGINT, `feature_67` BIGINT, `feature_68` BIGINT, `feature_69` BIGINT, `feature_70` BIGINT, `feature_71` BIGINT, `feature_72` BIGINT, `feature_73` BIGINT, `feature_74` BIGINT, `feature_75` BIGINT, `feature_76` BIGINT, `feature_77` BIGINT, `feature_78` BIGINT, `feature_79` BIGINT, `feature_80` BIGINT, `target` VARCHAR(255), `encounter_id` BIGINT, `patient_nbr` BIGINT
        )
        , parameters: None
[2025-05-03T07:48:38.589+0000] {sql.py:466} INFO - Rows affected: 0
[2025-05-03T07:48:38.596+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:48:49.986+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:48:49.993+0000] {sql.py:457} INFO - Running statement: SELECT COUNT(*) as count FROM diabetes_test_processed, parameters: None
[2025-05-03T07:48:50.018+0000] {sql.py:466} INFO - Rows affected: 1
[2025-05-03T07:48:50.023+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:407: AirflowProviderDeprecationWarning: Call to deprecated method _make_common_data_structure. (The `_make_serializable` method is deprecated and support will be removed in a future version of the common.sql provider. Please update the DbApiHook's provider to a version based on common.sql >= 1.9.1.)
  result = self._make_common_data_structure(handler(cur))

[2025-05-03T07:48:50.025+0000] {process_and_clean_data.py:658} ERROR - âœ— Error al guardar datos en tabla diabetes_test_processed: tuple indices must be integers or slices, not str
[2025-05-03T07:48:50.026+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T07:48:50.026+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/process_and_clean_data.py", line 650, in save_processed_table
    rows_inserted = result[0]['count']
TypeError: tuple indices must be integers or slices, not str
[2025-05-03T07:48:50.038+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=diabetes_data_pipeline, task_id=save_test_data, execution_date=20250503T074433, start_date=20250503T074836, end_date=20250503T074850
[2025-05-03T07:48:50.075+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 235 for task save_test_data (tuple indices must be integers or slices, not str; 1671)
[2025-05-03T07:48:50.189+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T07:48:50.240+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T07:48:50.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
